config/routes.rb
Rails.application.routes.draw do
  root to: 'chats#index'
  resources :chats

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  def index
    if session[:chat].nil?
      @chat = Chat.new()
    else
      @bot = Chat.new({'content' => session[:chat]['content']})
      @chat = Chat.new()
      session[:chat] = nil
    end
  end

  def first_entity_value(entities, entity)
    return nil unless entities.has_key? entity
    val = entities[entity][0]['value']
    return nil if val.nil?
    return val.is_a?(Hash) ? val['value'] : val
  end

  def create
    chat = Chat.new(chat_params)
    @msg = {}
    wit_actions = {
      :say => -> (session_id, context, msg) {
        @msg['message'] = msg
      },
      :merge => -> (session_id, context, entities, msg) {
        loc = first_entity_value entities, 'location'
        context['loc'] = loc unless loc.nil?
        gintama = first_entity_value entities, 'gintama'
        context['gintama'] = gintama unless gintama.nil?
        kimono = first_entity_value entities, 'kimono'
        context['kimono'] = kimono unless kimono.nil?
        return context
      },
      :error => -> (session_id, context, error) {
        p error.message
      },
    }
    wit = Wit.new('NXJJAH33CJFJUHCX7XXRGILI3MW5WWS5', wit_actions)
    @run_actions = wit.run_actions('123abc', {}, {})
    message = wit.message(chat.content)
    run_actions = wit.run_actions('123abc', chat.content, {})
    bot = Chat.new({"content" => @msg["message"], "user_type" => "bot"})
    session[:chat] = {'content' => @msg["message"]}
    redirect_to root_path
  end

  private
    def set_chat
      @chat = Chat.find(params[:id])
    end

    def chat_params
      params.require(:chat).permit(:content, :user_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.haml
= form_for @chat do |f|
  - if @chat.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chat.errors.count, "error")} prohibited this chat from being saved:"
      %ul
        - @chat.errors.full_messages.each do |msg|
          %li= msg

  .field_box
    = f.text_field :content
    = f.hidden_field :user_type, value: "user"

  .actions
    = f.submit 'Save'

app/views/chats/edit.html.haml
%h1 Editing chat

= render 'form'

= link_to 'Show', @chat
\|
= link_to 'Back', chats_path

app/views/chats/index.html.haml
- if @bot.present?
  = @bot.content
- else
  %p Hey, I'm "AI-TAISHO"
= render partial: 'form'

app/views/chats/new.html.haml
%h1 New chat

= render 'form'

= link_to 'Back', chats_path

app/views/chats/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_chat_path(@chat)
\|
= link_to 'Back', chats_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Spajam
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield